#!/bin/bash

##
# clockUtils
# Copyright (2015) Michael Baer, Daniel Bonrath, All rights reserved.
#
# This file is part of clockUtils; clockUtils is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
##

set -e

# make sure this doesn't get called directly
if [ "`basename "${0}"`" == "build-common.sh" ]; then
	echo "This script should not be called directly. Please execute build-dependencies.sh instead" >&2
	exit 1
fi

# parse arguments

# usage
usage() {
	echo "Usage: ${0} [OPTIONS]" >&2
	echo >&2
	echo "Possible options are:" >&2
	echo "  -h,   --help          displays this help message" >&2
	echo "  -j n, --parallel=n    enables parallel building with n processes" >&2
	echo "  -r,   --release       disables building the debug versions of libs" >&2
	echo "  -c,   --clean         removes all files generated by these scripts" >&2
}

# only parse arguments the first time this script is called
if [ -z "${ARGS_PARSED}" ]; then
	# default parameters
	export BUILD_PARALLEL="$(grep processor -c /proc/cpuinfo)"
	export CLEAN=""

	# option strings
	LONG_OPTS="help,parallel:,release,clean"
	SHORT_OPTS="hj:rc"
	ARGS=$( getopt -n "`basename ${0}`" -l "${LONG_OPTS}" -o "${SHORT_OPTS}" -- "$@" )
	if [[ $? != 0 ]]; then
		usage
		exit 1
	fi
	eval set -- "${ARGS}"
	for i; do
		case "${i}" in
			-h|--help)
				usage;
				exit 1;
				;;
			-j|--parallel)
				shift;
				BUILD_PARALLEL=$(( $1 + 0 ));
				shift;
				;;
			-r|--release)
				shift;
				DEBUG=""
				M2ETIS_DEBUG="ON"
				;;
			-c|--clean)
				shift;
				CLEAN="1"
				;;
		esac
	done

	export ARGS_PARSED=1
fi

# shared variables
DEP_DIR="${PWD}"
EX_DIR="${PWD}/../externals/libs/"
PATCH_DIR="${PWD}/../externals/patches/"
BUILD_ROOT="/tmp/`whoami`"
C_COMPILER=gcc
CXX_COMPILER=g++

if [ "${2}" = "--" ] ; then
	C_COMPILER=gcc
	CXX_COMPILER=g++
	DEP_OUT_DIR=${DEP_DIR}/gcc
fi
if [ "${2}" = "gcc" ] ; then
	C_COMPILER=gcc
	CXX_COMPILER=g++
	DEP_OUT_DIR=${DEP_DIR}/gcc
fi
if [ "${2}" = "clang" ] ; then
	C_COMPILER=clang
	CXX_COMPILER=clang++
	DEP_OUT_DIR=${DEP_DIR}/clang
fi


mkdir -p "${BUILD_ROOT}"

# print titles
title() {
	text="$1"
	echo
	echo
	echo "${text}"
	echo
	echo
}

# print status text
status() {
	text="${1}"
	echo "	${text}"
}

# check whether dependencies are up to date
uptodate() {
	reference="${1}"
	target="${2}"
	if [ ! -d "${target}" ]; then
		# hasn't even been built at all yet
		return 0;
	fi

	mtime_reference=`stat -c '%Y' "${reference}"`
	mtime_target=`stat -c '%Y' "${target}"`
	#echo "Comparing ${reference} and ${target}"
	if [ "${mtime_reference}" -gt "${mtime_target}" ]; then
		#echo "outdated"
		return 0;
	else
		#echo "up to date"
		return 1;
	fi
}
